### ISSUE TITLE
Per environment configuration via wp-config.php?

### ISSUE THREAD

**Issue by ari-gold** [ashfame/email-cop#5]
Any thoughts/plans to provide the ability to configure per environment via code, in wp-config.php?

Drupal's [reroute_email](https://www.drupal.org/project/reroute_email), for example, allows you to setup configuration in settings.php that will prevent you from spamming people when pulling the database back from Live to Dev or Test and makes sure email will always be rerouted in when not in Live/Production.

**Comment by ashfame** [comment]
I would love to have that in, but unfortunately that requires some sort of constants where plugin can determine the environment its running in.

For my purpose, I have environment specific constants defined and I do it in the following way:

```
add_action( 'init', 'dlp_enforce_plugin_state' );

function dlp_enforce_plugin_state() {
    if ( WP_LOCAL_SERVER ) {
        $plugins = get_option( 'active_plugins' );
        if ( ! in_array( 'email-cop/plugin.php', $plugins ) ) {
            $plugins[] = 'email-cop/plugin.php';
            update_option( 'active_plugins', $plugins );
        }
    }
}
```

**Comment by ashfame** [comment]
And not to mention the ability to run code which would be outside plugin and can enable plugin when a database is pulled from live or other environment based off a constant / condition.
